name       : haskell-regex-base
version    : 0.94.0.0
release    : 6
source     :
    - https://hackage.haskell.org/package/regex-base-0.94.0.0/regex-base-0.94.0.0.tar.gz : c41f82f5fc1157c961a4cbdc0cd5561e5aa44f339ce6e706d978d97e0ca6b914
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface API for regex-posix,pcre,parsec,tdfa,dfa
description: |
    Interface API for regex-posix,pcre,parsec,tdfa,dfa
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
