name       : haskell-regex-base
version    : 0.93.2
release    : 5
source     :
    - http://hackage.haskell.org/package/regex-base-0.93.2/regex-base-0.93.2.tar.gz : 20dc5713a16f3d5e2e6d056b4beb9cfdc4368cd09fd56f47414c847705243278
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface API for regex-posix,pcre,parsec,tdfa,dfa
description: "Interface API for regex-posix,pcre,parsec,tdfa,dfa \n"
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
