name       : haskell-regex-base
version    : 0.93.2
release    : 1
source     :
    - http://hackage.haskell.org/package/regex-base-0.93.2/regex-base-0.93.2.tar.gz : 20dc5713a16f3d5e2e6d056b4beb9cfdc4368cd09fd56f47414c847705243278
license    : BSD-3-Clause
component  : programming
summary    : Interface API for regex-posix,pcre,parsec,tdfa,dfa 
description: |
    Interface API for regex-posix,pcre,parsec,tdfa,dfa 
builddeps  :
    - ghc
    - haskell-mtl
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc

build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 regex-base-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/regex-base-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/regex-base-$version/*.a
