name       : haskell-regex-base
version    : 0.94.0.2
release    : 7
source     :
    - https://hackage.haskell.org/package/regex-base-0.94.0.2/regex-base-0.94.0.2.tar.gz : 7b99408f580f5bb67a1c413e0bc735886608251331ad36322020f2169aea2ef1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface API for regex-posix,pcre,parsec,tdfa,dfa
description: |
    Interface API for regex-posix,pcre,parsec,tdfa,dfa
builddeps  :
    - ghc-devel
setup      : |
    cp $pkgfiles/2.cabal regex-base.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
